/**
 * Smart API Key Health Monitor
 * 
 * Monitors the health, performance, and status of all API connections
 * with real-time metrics and intelligent alerting.
 */

import { geminiKeyGenerator } from './geminiKeyGenerator';

interface ApiKeyMetrics {
  responseTime: number;
  uptime: number;
  errorCount: number;
  successCount: number;
  lastChecked: Date;
  quotaUsed?: number;
  quotaLimit?: number;
}

interface ApiKeyStatus {
  id: string;
  name: string;
  provider: string;
  status: 'active' | 'inactive' | 'error' | 'warning' | 'checking';
  isConfigured: boolean;
  isAutoGenerated?: boolean;
  model?: string;
  isTemporary?: boolean;
  expiresAt?: Date;
  metrics: ApiKeyMetrics;
}

interface HealthMetrics {
  overallHealth: number;
  activeKeys: number;
  totalKeys: number;
  avgResponseTime: number;
  totalRequests: number;
  successfulRequests: number;
}

class ApiKeyHealthMonitor {
  private keyStatuses: Map<string, ApiKeyStatus> = new Map();
  private monitoringInterval: NodeJS.Timeout | null = null;
  private lastHealthCheck: Date = new Date();

  constructor() {
    this.initializeMonitoring();
  }

  /**
   * Initialize continuous monitoring of all API keys
   */
  private initializeMonitoring() {
    // Initial check
    this.checkAllKeys();
    
    // Set up periodic monitoring every 30 seconds
    this.monitoringInterval = setInterval(() => {
      this.checkAllKeys();
    }, 30000);
    
    console.log('🔍 API Key Health Monitor iniciado');
  }

  /**
   * Check the health of all configured API keys
   */
  private async checkAllKeys() {
    try {
      console.log('🔍 Verificando salud de todas las claves API...');
      
      // Check Gemini API
      await this.checkGeminiKey();
      
      // Check OpenAI API
      await this.checkOpenAIKey();
      
      // Check WhatsApp API
      await this.checkWhatsAppKey();
      
      // Check Database connection
      await this.checkDatabaseConnection();
      
      this.lastHealthCheck = new Date();
      console.log('✅ Verificación de salud completada');
      
    } catch (error) {
      console.error('❌ Error en verificación de salud:', error);
    }
  }

  /**
   * Check Gemini API key status and performance
   */
  private async checkGeminiKey() {
    const startTime = Date.now();
    const keyId = 'gemini_api';
    
    try {
      // Get current status from generator
      const keyInfo = await geminiKeyGenerator.getValidKey();
      
      if (keyInfo && keyInfo.key) {
        // Test API with a simple request
        const response = await fetch('https://generativelanguage.googleapis.com/v1beta/models', {
          headers: {
            'x-goog-api-key': keyInfo.key
          }
        });
        
        const responseTime = Date.now() - startTime;
        
        if (response.ok) {
          this.updateKeyStatus(keyId, {
            id: keyId,
            name: 'Gemini AI Pro',
            provider: 'Google',
            status: 'active',
            isConfigured: true,
            isAutoGenerated: true,
            model: keyInfo.model,
            isTemporary: keyInfo.isTemporary,
            expiresAt: keyInfo.expiresAt,
            metrics: {
              responseTime,
              uptime: this.calculateUptime(keyId),
              errorCount: this.getErrorCount(keyId),
              successCount: this.incrementSuccessCount(keyId),
              lastChecked: new Date(),
              quotaUsed: keyInfo.quotaStatus === 'exhausted' ? 100 : 
                        keyInfo.quotaStatus === 'limited' ? 80 : 20,
              quotaLimit: 100
            }
          });
        } else {
          throw new Error(`HTTP ${response.status}`);
        }
      } else {
        throw new Error('No API key available');
      }
    } catch (error) {
      console.error('❌ Error verificando Gemini API:', error);
      this.updateKeyStatus(keyId, {
        id: keyId,
        name: 'Gemini AI Pro',
        provider: 'Google',
        status: 'error',
        isConfigured: false,
        metrics: {
          responseTime: Date.now() - startTime,
          uptime: this.calculateUptime(keyId),
          errorCount: this.incrementErrorCount(keyId),
          successCount: this.getSuccessCount(keyId),
          lastChecked: new Date()
        }
      });
    }
  }

  /**
   * Check OpenAI API key status
   */
  private async checkOpenAIKey() {
    const startTime = Date.now();
    const keyId = 'openai_api';
    const apiKey = process.env.OPENAI_API_KEY;
    
    try {
      if (!apiKey) {
        throw new Error('OpenAI API key not configured');
      }

      const response = await fetch('https://api.openai.com/v1/models', {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        }
      });
      
      const responseTime = Date.now() - startTime;
      
      if (response.ok) {
        this.updateKeyStatus(keyId, {
          id: keyId,
          name: 'OpenAI GPT',
          provider: 'OpenAI',
          status: 'active',
          isConfigured: true,
          isAutoGenerated: false,
          model: 'gpt-4',
          metrics: {
            responseTime,
            uptime: this.calculateUptime(keyId),
            errorCount: this.getErrorCount(keyId),
            successCount: this.incrementSuccessCount(keyId),
            lastChecked: new Date()
          }
        });
      } else {
        throw new Error(`HTTP ${response.status}`);
      }
    } catch (error) {
      console.error('❌ Error verificando OpenAI API:', error);
      this.updateKeyStatus(keyId, {
        id: keyId,
        name: 'OpenAI GPT',
        provider: 'OpenAI',
        status: apiKey ? 'error' : 'inactive',
        isConfigured: !!apiKey,
        metrics: {
          responseTime: Date.now() - startTime,
          uptime: this.calculateUptime(keyId),
          errorCount: this.incrementErrorCount(keyId),
          successCount: this.getSuccessCount(keyId),
          lastChecked: new Date()
        }
      });
    }
  }

  /**
   * Check WhatsApp connection status
   */
  private async checkWhatsAppKey() {
    const startTime = Date.now();
    const keyId = 'whatsapp_api';
    
    try {
      // Check if WhatsApp service is available
      const response = await fetch('http://localhost:5000/api/integrations/whatsapp/status');
      const data = await response.json();
      
      const responseTime = Date.now() - startTime;
      const isConnected = data.success && data.accounts?.some((account: any) => account.status === 'connected');
      
      this.updateKeyStatus(keyId, {
        id: keyId,
        name: 'WhatsApp Business',
        provider: 'Meta',
        status: isConnected ? 'active' : 'warning',
        isConfigured: true,
        isAutoGenerated: false,
        metrics: {
          responseTime,
          uptime: this.calculateUptime(keyId),
          errorCount: isConnected ? this.getErrorCount(keyId) : this.incrementErrorCount(keyId),
          successCount: isConnected ? this.incrementSuccessCount(keyId) : this.getSuccessCount(keyId),
          lastChecked: new Date()
        }
      });
    } catch (error) {
      console.error('❌ Error verificando WhatsApp API:', error);
      this.updateKeyStatus(keyId, {
        id: keyId,
        name: 'WhatsApp Business',
        provider: 'Meta',
        status: 'error',
        isConfigured: true,
        metrics: {
          responseTime: Date.now() - startTime,
          uptime: this.calculateUptime(keyId),
          errorCount: this.incrementErrorCount(keyId),
          successCount: this.getSuccessCount(keyId),
          lastChecked: new Date()
        }
      });
    }
  }

  /**
   * Check database connection health
   */
  private async checkDatabaseConnection() {
    const startTime = Date.now();
    const keyId = 'database_connection';
    
    try {
      // Import database connection
      const { pool } = await import('../db');
      
      // Simple query to test connection
      const result = await pool.query('SELECT 1 as test');
      const responseTime = Date.now() - startTime;
      
      if (result.rows[0]?.test === 1) {
        this.updateKeyStatus(keyId, {
          id: keyId,
          name: 'PostgreSQL Database',
          provider: 'PostgreSQL',
          status: 'active',
          isConfigured: true,
          isAutoGenerated: false,
          metrics: {
            responseTime,
            uptime: this.calculateUptime(keyId),
            errorCount: this.getErrorCount(keyId),
            successCount: this.incrementSuccessCount(keyId),
            lastChecked: new Date()
          }
        });
      } else {
        throw new Error('Database query failed');
      }
    } catch (error) {
      console.error('❌ Error verificando base de datos:', error);
      this.updateKeyStatus(keyId, {
        id: keyId,
        name: 'PostgreSQL Database',
        provider: 'PostgreSQL',
        status: 'error',
        isConfigured: true,
        metrics: {
          responseTime: Date.now() - startTime,
          uptime: this.calculateUptime(keyId),
          errorCount: this.incrementErrorCount(keyId),
          successCount: this.getSuccessCount(keyId),
          lastChecked: new Date()
        }
      });
    }
  }

  /**
   * Update the status of a specific API key
   */
  private updateKeyStatus(keyId: string, status: ApiKeyStatus) {
    this.keyStatuses.set(keyId, status);
  }

  /**
   * Calculate uptime percentage for a key
   */
  private calculateUptime(keyId: string): number {
    const status = this.keyStatuses.get(keyId);
    if (!status) return 100;
    
    const totalChecks = status.metrics.successCount + status.metrics.errorCount;
    if (totalChecks === 0) return 100;
    
    return Math.round((status.metrics.successCount / totalChecks) * 100);
  }

  /**
   * Get current error count for a key
   */
  private getErrorCount(keyId: string): number {
    return this.keyStatuses.get(keyId)?.metrics.errorCount || 0;
  }

  /**
   * Increment error count for a key
   */
  private incrementErrorCount(keyId: string): number {
    const current = this.getErrorCount(keyId);
    return current + 1;
  }

  /**
   * Get current success count for a key
   */
  private getSuccessCount(keyId: string): number {
    return this.keyStatuses.get(keyId)?.metrics.successCount || 0;
  }

  /**
   * Increment success count for a key
   */
  private incrementSuccessCount(keyId: string): number {
    const current = this.getSuccessCount(keyId);
    return current + 1;
  }

  /**
   * Get overall health metrics
   */
  public getHealthMetrics(): HealthMetrics {
    const statuses = Array.from(this.keyStatuses.values());
    const activeKeys = statuses.filter(s => s.status === 'active').length;
    const totalKeys = statuses.length;
    
    const totalResponseTime = statuses.reduce((sum, s) => sum + s.metrics.responseTime, 0);
    const avgResponseTime = totalKeys > 0 ? Math.round(totalResponseTime / totalKeys) : 0;
    
    const totalRequests = statuses.reduce((sum, s) => sum + s.metrics.successCount + s.metrics.errorCount, 0);
    const successfulRequests = statuses.reduce((sum, s) => sum + s.metrics.successCount, 0);
    
    const overallHealth = totalKeys > 0 ? Math.round((activeKeys / totalKeys) * 100) : 100;
    
    return {
      overallHealth,
      activeKeys,
      totalKeys,
      avgResponseTime,
      totalRequests,
      successfulRequests
    };
  }

  /**
   * Get all API key statuses
   */
  public getAllKeyStatuses(): ApiKeyStatus[] {
    return Array.from(this.keyStatuses.values());
  }

  /**
   * Test a specific API key
   */
  public async testApiKey(keyId: string): Promise<{ success: boolean; responseTime: number; error?: string }> {
    const startTime = Date.now();
    
    try {
      switch (keyId) {
        case 'gemini_api':
          await this.checkGeminiKey();
          break;
        case 'openai_api':
          await this.checkOpenAIKey();
          break;
        case 'whatsapp_api':
          await this.checkWhatsAppKey();
          break;
        case 'database_connection':
          await this.checkDatabaseConnection();
          break;
        default:
          throw new Error('Unknown API key');
      }
      
      const status = this.keyStatuses.get(keyId);
      const responseTime = Date.now() - startTime;
      
      return {
        success: status?.status === 'active',
        responseTime,
        error: status?.status !== 'active' ? 'API key test failed' : undefined
      };
    } catch (error: any) {
      return {
        success: false,
        responseTime: Date.now() - startTime,
        error: error.message
      };
    }
  }

  /**
   * Regenerate a specific API key (if supported)
   */
  public async regenerateApiKey(keyId: string): Promise<{ success: boolean; message: string }> {
    try {
      switch (keyId) {
        case 'gemini_api':
          await geminiKeyGenerator.forceRegenerate();
          await this.checkGeminiKey();
          return {
            success: true,
            message: 'Clave Gemini regenerada automáticamente'
          };
        default:
          return {
            success: false,
            message: 'Regeneración no soportada para esta clave'
          };
      }
    } catch (error: any) {
      return {
        success: false,
        message: error.message || 'Error regenerando clave API'
      };
    }
  }

  /**
   * Cleanup monitoring resources
   */
  public destroy() {
    if (this.monitoringInterval) {
      clearInterval(this.monitoringInterval);
      this.monitoringInterval = null;
    }
    console.log('🔍 API Key Health Monitor detenido');
  }
}

// Export singleton instance
export const apiKeyHealthMonitor = new ApiKeyHealthMonitor();