import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { 
  Key, 
  Activity, 
  CheckCircle, 
  AlertTriangle, 
  RefreshCw, 
  Settings, 
  Zap, 
  Clock, 
  TrendingUp,
  Wifi,
  WifiOff,
  Database,
  Brain,
  MessageSquare,
  Shield,
  BarChart3,
  Eye,
  EyeOff
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ApiKeyStatus {
  id: string;
  name: string;
  provider: string;
  status: 'active' | 'inactive' | 'error' | 'warning' | 'checking';
  isConfigured: boolean;
  isAutoGenerated?: boolean;
  quotaUsed?: number;
  quotaLimit?: number;
  lastChecked: Date;
  responseTime?: number;
  uptime?: number;
  errorCount?: number;
  successRate?: number;
  model?: string;
  isTemporary?: boolean;
  expiresAt?: Date;
}

interface HealthMetrics {
  overallHealth: number;
  activeKeys: number;
  totalKeys: number;
  avgResponseTime: number;
  totalRequests: number;
  successfulRequests: number;
}

export function ApiKeyManagement() {
  const [apiKeys, setApiKeys] = useState<ApiKeyStatus[]>([]);
  const [healthMetrics, setHealthMetrics] = useState<HealthMetrics | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [showKeyDialog, setShowKeyDialog] = useState(false);
  const [selectedKey, setSelectedKey] = useState<ApiKeyStatus | null>(null);
  const [newKeyData, setNewKeyData] = useState({
    provider: '',
    apiKey: '',
    name: ''
  });
  const [showApiKeys, setShowApiKeys] = useState<{[key: string]: boolean}>({});
  
  const { toast } = useToast();

  useEffect(() => {
    checkAllApiKeys();
    const interval = setInterval(checkAllApiKeys, 30000); // Check every 30 seconds
    return () => clearInterval(interval);
  }, []);

  const checkAllApiKeys = async () => {
    setIsLoading(true);
    try {
      const response = await fetch('/api/settings/api-keys-health');
      const data = await response.json();
      
      if (data.success) {
        setApiKeys(data.keys);
        setHealthMetrics(data.metrics);
      }
    } catch (error) {
      console.error('Error checking API keys health:', error);
    }
    setIsLoading(false);
  };

  const regenerateKey = async (keyId: string) => {
    try {
      const response = await fetch(`/api/settings/regenerate-key/${keyId}`, {
        method: 'POST'
      });
      
      const data = await response.json();
      
      if (data.success) {
        toast({
          title: "Clave regenerada",
          description: "La clave API ha sido regenerada exitosamente",
        });
        checkAllApiKeys();
      } else {
        throw new Error(data.message);
      }
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Error regenerando la clave API",
        variant: "destructive",
      });
    }
  };

  const testApiKey = async (keyId: string) => {
    try {
      const response = await fetch(`/api/settings/test-key/${keyId}`, {
        method: 'POST'
      });
      
      const data = await response.json();
      
      if (data.success) {
        toast({
          title: "Prueba exitosa",
          description: `Clave API funcional - Tiempo de respuesta: ${data.responseTime}ms`,
        });
      } else {
        toast({
          title: "Prueba fallida",
          description: data.error || "La clave API no responde correctamente",
          variant: "destructive",
        });
      }
      
      checkAllApiKeys();
    } catch (error: any) {
      toast({
        title: "Error en prueba",
        description: "No se pudo probar la clave API",
        variant: "destructive",
      });
    }
  };

  const addNewApiKey = async () => {
    try {
      const response = await fetch('/api/settings/add-api-key', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(newKeyData)
      });
      
      const data = await response.json();
      
      if (data.success) {
        toast({
          title: "Clave agregada",
          description: "Nueva clave API configurada exitosamente",
        });
        setShowAddDialog(false);
        setNewKeyData({ provider: '', apiKey: '', name: '' });
        checkAllApiKeys();
      } else {
        throw new Error(data.message);
      }
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Error agregando la clave API",
        variant: "destructive",
      });
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500 hover:bg-green-600';
      case 'warning': return 'bg-yellow-500 hover:bg-yellow-600';
      case 'error': return 'bg-red-500 hover:bg-red-600';
      case 'inactive': return 'bg-gray-500 hover:bg-gray-600';
      case 'checking': return 'bg-blue-500 hover:bg-blue-600';
      default: return 'bg-gray-500 hover:bg-gray-600';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'active': return <CheckCircle className="h-4 w-4" />;
      case 'warning': return <AlertTriangle className="h-4 w-4" />;
      case 'error': return <WifiOff className="h-4 w-4" />;
      case 'inactive': return <WifiOff className="h-4 w-4" />;
      case 'checking': return <RefreshCw className="h-4 w-4 animate-spin" />;
      default: return <Key className="h-4 w-4" />;
    }
  };

  const getProviderIcon = (provider: string) => {
    switch (provider.toLowerCase()) {
      case 'gemini': return <Brain className="h-5 w-5 text-blue-600" />;
      case 'openai': return <MessageSquare className="h-5 w-5 text-green-600" />;
      case 'whatsapp': return <Wifi className="h-5 w-5 text-green-500" />;
      case 'database': return <Database className="h-5 w-5 text-purple-600" />;
      default: return <Key className="h-5 w-5 text-gray-600" />;
    }
  };

  const formatUptime = (uptime: number) => {
    if (uptime >= 99) return '99.9%';
    return `${uptime.toFixed(1)}%`;
  };

  const toggleKeyVisibility = (keyId: string) => {
    setShowApiKeys(prev => ({
      ...prev,
      [keyId]: !prev[keyId]
    }));
  };

  const maskApiKey = (key: string, isVisible: boolean) => {
    if (isVisible) return key;
    if (key.length <= 8) return '••••••••';
    return key.substring(0, 4) + '••••••••' + key.substring(key.length - 4);
  };

  return (
    <div className="container mx-auto p-6 max-w-7xl space-y-6">
      {/* Header with Overall Health */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Shield className="h-6 w-6 text-blue-600" />
              <span>Gestión Inteligente de Claves API</span>
            </div>
            <Button onClick={checkAllApiKeys} disabled={isLoading} size="sm">
              <RefreshCw className={`h-4 w-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
              Actualizar
            </Button>
          </CardTitle>
          <CardDescription>
            Monitoreo en tiempo real del estado y rendimiento de todas las conexiones API
          </CardDescription>
        </CardHeader>
        
        {healthMetrics && (
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
              <div className="text-center p-4 bg-blue-50 rounded-lg">
                <div className="text-2xl font-bold text-blue-600">{healthMetrics.overallHealth}%</div>
                <div className="text-sm text-blue-700">Salud General</div>
                <Progress value={healthMetrics.overallHealth} className="mt-2 h-2" />
              </div>
              <div className="text-center p-4 bg-green-50 rounded-lg">
                <div className="text-2xl font-bold text-green-600">{healthMetrics.activeKeys}/{healthMetrics.totalKeys}</div>
                <div className="text-sm text-green-700">APIs Activas</div>
              </div>
              <div className="text-center p-4 bg-purple-50 rounded-lg">
                <div className="text-2xl font-bold text-purple-600">{healthMetrics.avgResponseTime}ms</div>
                <div className="text-sm text-purple-700">Tiempo Promedio</div>
              </div>
              <div className="text-center p-4 bg-orange-50 rounded-lg">
                <div className="text-2xl font-bold text-orange-600">
                  {healthMetrics.totalRequests > 0 ? 
                    Math.round((healthMetrics.successfulRequests / healthMetrics.totalRequests) * 100) : 0}%
                </div>
                <div className="text-sm text-orange-700">Tasa de Éxito</div>
              </div>
            </div>
          </CardContent>
        )}
      </Card>

      {/* API Keys Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {apiKeys.map((key) => (
          <Card key={key.id} className="hover:shadow-lg transition-shadow">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center justify-between text-lg">
                <div className="flex items-center gap-2">
                  {getProviderIcon(key.provider)}
                  <span>{key.name}</span>
                </div>
                <Badge className={getStatusColor(key.status)}>
                  {getStatusIcon(key.status)}
                  <span className="ml-1 capitalize">{key.status}</span>
                </Badge>
              </CardTitle>
              <CardDescription>
                {key.provider} • {key.isAutoGenerated ? 'Auto-generada' : 'Manual'}
              </CardDescription>
            </CardHeader>
            
            <CardContent className="space-y-4">
              {/* Key Info */}
              {key.isConfigured && (
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label className="text-xs text-gray-600">Clave API:</Label>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => toggleKeyVisibility(key.id)}
                      className="h-6 w-6 p-0"
                    >
                      {showApiKeys[key.id] ? <EyeOff className="h-3 w-3" /> : <Eye className="h-3 w-3" />}
                    </Button>
                  </div>
                  <div className="text-xs font-mono bg-gray-100 p-2 rounded">
                    {maskApiKey(key.id, showApiKeys[key.id])}
                  </div>
                </div>
              )}

              {/* Model Info */}
              {key.model && (
                <div>
                  <Label className="text-xs text-gray-600">Modelo:</Label>
                  <div className="text-sm font-medium">{key.model}</div>
                </div>
              )}

              {/* Quota Usage */}
              {key.quotaUsed !== undefined && key.quotaLimit !== undefined && (
                <div>
                  <Label className="text-xs text-gray-600">Uso de Cuota:</Label>
                  <div className="flex items-center gap-2">
                    <Progress 
                      value={(key.quotaUsed / key.quotaLimit) * 100} 
                      className="flex-1 h-2"
                    />
                    <span className="text-xs">
                      {key.quotaUsed}/{key.quotaLimit}
                    </span>
                  </div>
                </div>
              )}

              {/* Performance Metrics */}
              <div className="grid grid-cols-2 gap-4 text-center">
                {key.responseTime !== undefined && (
                  <div>
                    <div className="text-lg font-bold text-blue-600">{key.responseTime}ms</div>
                    <div className="text-xs text-gray-600">Respuesta</div>
                  </div>
                )}
                {key.uptime !== undefined && (
                  <div>
                    <div className="text-lg font-bold text-green-600">{formatUptime(key.uptime)}</div>
                    <div className="text-xs text-gray-600">Uptime</div>
                  </div>
                )}
              </div>

              {/* Expiration Warning */}
              {key.isTemporary && key.expiresAt && (
                <div className="p-2 bg-yellow-50 border border-yellow-200 rounded">
                  <div className="flex items-center gap-2 text-yellow-700">
                    <Clock className="h-4 w-4" />
                    <span className="text-xs">
                      Expira: {new Date(key.expiresAt).toLocaleString()}
                    </span>
                  </div>
                </div>
              )}

              <Separator />

              {/* Action Buttons */}
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => testApiKey(key.id)}
                  className="flex-1"
                >
                  <Activity className="h-3 w-3 mr-1" />
                  Probar
                </Button>
                
                {key.isAutoGenerated && (
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => regenerateKey(key.id)}
                    className="flex-1"
                  >
                    <RefreshCw className="h-3 w-3 mr-1" />
                    Regenerar
                  </Button>
                )}
                
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    setSelectedKey(key);
                    setShowKeyDialog(true);
                  }}
                >
                  <Settings className="h-3 w-3" />
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}

        {/* Add New Key Card */}
        <Card className="border-dashed border-2 hover:border-blue-500 transition-colors cursor-pointer">
          <CardContent 
            className="flex flex-col items-center justify-center h-full min-h-[200px] text-center"
            onClick={() => setShowAddDialog(true)}
          >
            <div className="w-12 h-12 rounded-full bg-blue-100 flex items-center justify-center mb-4">
              <Key className="h-6 w-6 text-blue-600" />
            </div>
            <h3 className="font-medium mb-2">Agregar Nueva API</h3>
            <p className="text-sm text-gray-600">
              Configura una nueva conexión API para ampliar las capacidades del sistema
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Add New API Key Dialog */}
      <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Agregar Nueva Clave API</DialogTitle>
            <DialogDescription>
              Configura una nueva conexión API para el sistema
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="provider">Proveedor</Label>
              <Select
                value={newKeyData.provider}
                onValueChange={(value) => setNewKeyData(prev => ({ ...prev, provider: value }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Selecciona un proveedor" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="openai">OpenAI</SelectItem>
                  <SelectItem value="gemini">Google Gemini</SelectItem>
                  <SelectItem value="claude">Anthropic Claude</SelectItem>
                  <SelectItem value="custom">Personalizado</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="name">Nombre</Label>
              <Input
                id="name"
                value={newKeyData.name}
                onChange={(e) => setNewKeyData(prev => ({ ...prev, name: e.target.value }))}
                placeholder="Nombre descriptivo"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="apiKey">Clave API</Label>
              <Input
                id="apiKey"
                type="password"
                value={newKeyData.apiKey}
                onChange={(e) => setNewKeyData(prev => ({ ...prev, apiKey: e.target.value }))}
                placeholder="Pega tu clave API aquí"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAddDialog(false)}>
              Cancelar
            </Button>
            <Button 
              onClick={addNewApiKey}
              disabled={!newKeyData.provider || !newKeyData.name || !newKeyData.apiKey}
            >
              Agregar Clave
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Key Details Dialog */}
      <Dialog open={showKeyDialog} onOpenChange={setShowKeyDialog}>
        <DialogContent className="sm:max-w-[500px]">
          {selectedKey && (
            <>
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  {getProviderIcon(selectedKey.provider)}
                  {selectedKey.name}
                </DialogTitle>
                <DialogDescription>
                  Detalles y configuración de la clave API
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-sm text-gray-600">Estado</Label>
                    <Badge className={getStatusColor(selectedKey.status)}>
                      {getStatusIcon(selectedKey.status)}
                      <span className="ml-1 capitalize">{selectedKey.status}</span>
                    </Badge>
                  </div>
                  <div>
                    <Label className="text-sm text-gray-600">Proveedor</Label>
                    <div className="text-sm font-medium">{selectedKey.provider}</div>
                  </div>
                </div>
                
                {selectedKey.errorCount !== undefined && (
                  <div>
                    <Label className="text-sm text-gray-600">Errores Recientes</Label>
                    <div className="text-sm">{selectedKey.errorCount} errores</div>
                  </div>
                )}
                
                {selectedKey.successRate !== undefined && (
                  <div>
                    <Label className="text-sm text-gray-600">Tasa de Éxito</Label>
                    <div className="text-sm">{selectedKey.successRate.toFixed(1)}%</div>
                  </div>
                )}
                
                <div>
                  <Label className="text-sm text-gray-600">Última Verificación</Label>
                  <div className="text-sm">{selectedKey.lastChecked.toLocaleString()}</div>
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setShowKeyDialog(false)}>
                  Cerrar
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}